services:
  mysql:
    image: mysql:8.0
    container_name: xeno-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: xenodb
      MYSQL_USER: xenouser
      MYSQL_PASSWORD: xenopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - xeno-network

  rabbitmq:
      image: "rabbitmq:3-management"
      container_name: xeno-rabbitmq
      restart: always
      ports:
        - "15672:15672"  # RabbitMQ management UI
        - "5672:5672"    # RabbitMQ AMQP protocol
      networks:
        - xeno-network
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
        RABBITMQ_DEFAULT_VHOST: /
volumes:
  mysql_data:
    driver: local

networks:
  xeno-network:
    driver: bridge
